title: "Степан Шоболов | Авторская роспись стен и фасадов"
description: "Превращаю пустые стены в искусство. Уникальный арт для бизнеса."
url: "https://shobolov.com"
baseurl: ""

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/